### PR TITLE
Fix rowData not containing rownames

### PR DESCRIPTION
**Pull request by flying-sheep**

### CODE REVIEW

**Comment by LTLA** [comment]
See Bioconductor/SummarizedExperiment#2. The correct solution here would be for our `rowData` method to pass `...` onto that of the `SummarizedExperiment` getter.

**Comment by LTLA** [comment]
... which is now done, see 11f0a76272a0aac197d5933b30bd8e1c8d91eea7.

**Comment by flying-sheep** [comment]
Thank you! If they don't switch the default to `use.names = TRUE` however, this is still super confusing.

Of course, changing the default inside of SingleCellExperiment would probably make the confusion worse.

**Comment by LTLA** [comment]
Okay. I'm closing this, then - you can chase it up on the _SummarizedExperiment_ thread.

**Pull request closed without merging**
